name: 'Gas Diff Action'
description: 'Compares gas usage in Foundry projects and comments the changes on the PR'
inputs:
  token:
    description: 'GitHub token'
    required: true
  base_ref:
    description: 'Base branch reference'
    required: true
  head_ref:
    description: 'Head branch reference'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.head_ref }}
        fetch-depth: 0

    - name: Checkout base branch
      run: |
        git fetch origin ${{ inputs.base_ref }}
        git checkout ${{ inputs.base_ref }}
      shell: bash

    - name: Install Foundry
      uses: onbjerg/foundry-toolchain@v1
      with:
        version: nightly

    - name: Ensure .gas-snapshot exists
      run: |
        if [ ! -f .gas-snapshot ]; then
          forge snapshot
        fi
      shell: bash

    - name: Save base branch .gas-snapshot
      run: |
        cp .gas-snapshot .gas-snapshot-base
      shell: bash

    - name: Switch back to PR branch
      run: |
        git checkout --force ${{ inputs.head_ref }}
      shell: bash

    - name: Ensure .gas-snapshot exists on PR branch
      run: |
        if [ ! -f .gas-snapshot ]; then
          forge snapshot
        fi
      shell: bash

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      shell: bash
      run: | 
        cd ${{ github.action_path }}
        cargo build --release

    - name: Compare gas snapshots
      shell: bash
      run: |
        ${{ github.action_path }}//target/release/github-gas-action .gas-snapshot-base .gas-snapshot > comparison_output.txt

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Gas

    - name: Create or update comment on PR
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ inputs.token }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: 'comparison_output.txt'
        edit-mode: replace
